############# English navigation ##############

# main menu
[[main]]
name = "Page d'accueil"
url = "/"
weight = 1

[[main]]
name = "Nous contacter"
url = "/about"
weight = 2

[[main]]
name = "Carrière"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "Services"

[[main]]
parent = "Services"
name = "Digitalisation"
url = "/blog"

[[main]]
parent = "Services"
name = "AI"
url = "/contact"

[[main]]
parent = "Services"
name = "Expertise globale"
url = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
url = "/404"


# footer menu
[[footer]]
name = "Réseaux sociaux"
url = "/about"
weight = 1

[[footer]]
name = "Nous contacter"
url = "/elements"
weight = 2

[[footer]]
name = "Mentions légales"
url = "/privacy-policy"
weight = 3
